language_server_phpstan.enabled: true
language_server_php_cs_fixer.enabled: true
language_server_psalm.enabled: false
indexer.exclude_patterns:
  - "/vendor/**/Tests/**/*"
  - "/vendor/**/tests/**/*"
  - "/var/cache/**/*"
  - "/node_modules/**/*"
  - "/storage/**/*"
code_transform.import_globals: true
composer.autoload_deregister: true
symfony.enabled: false
language_server_completion.trim_leading_dollar: true
language_server.enable_workspace_symbols: true
language_server.diagnostics.on_update: true
language_server.diagnostics.on_save: true
language_server_phpstan.level: max
language_server_php_cs_fixer.bin: vendor/bin/php-cs-fixer
navigator.destinations:
  source: "app/<kernel>.php"
  test: "tests/<kernel>Test.php"
  implementation: "app/Implementations/<kernel>Implementation.php"
navigator.autocreate: true
language_server.diagnostic_providers:
  php-cs-fixer: true
  phpstan: true
completion_worse.completor.keyword.enabled: true
completion_worse.completor.named_parameter.enabled: true
completion_worse.completor.worse_reflection_class_tags.enabled: true
completion_worse.completor.worse_reflection_docblock.enabled: true
language_server_composer.enabled: true
